# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Isabela Leao
email: isabelaleao1985@gmail.com
description: Isabela Leão, originally from Maceió-AL, Brazil, holds a degree in Architecture. She has previously worked on designing houses, creating clothing collections and managing a restaurant. In recent years, she has decided to devote herself to painting, experimenting with different techniques and mediums. Currently, she has been blending her artistic production by exploring deeper and more melancholic themes while also creating animations with lighter and more amusing subjects.
baseurl: "/"
url: "https://isabelaleao.com"
twitter_username: isabelamleao
github_username: isabelaleao
instagram_username: isa.bela.leao

# Build settings
theme: minima
plugins:
  - jekyll-feed

# collections:
#   - animations

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
